name: "Run Black"

on:
    # Run this workflow for PRs into master or a release branch
    pull_request:
      branches:
        - master
        - release-*
    # Run on tagged releases
    push:
      tags:
        - '*'
    workflow_dispatch:

permissions:
    contents: write

jobs:
    run-black:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
          with:
            persist-credentials: true  # Needed to push changes

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.x"

        - name: Install Black
          run: pip install black

        - name: Detect current branch
          run: |
            if [ "${{ github.event_name }}" = "pull_request" ]; then
                # For PRs, use the source branch of the pull request
                echo "BRANCH_NAME=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
            else
                # Fallback for workflow_dispatch or other events
                echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
            fi

        - name: Run Black
          run: black .

        - name: Commit and push changes
          run: |
            if [[ -n "$(git status --porcelain)" ]]; then
                git config user.name "github-actions[bot]"
                git config user.email "github-actions[bot]@users.noreply.github.com"
        
                git add .
                git commit -m "chore: Black formatting"
        
                # Pull any new commits that appeared while we were running
                git pull --rebase origin "${{ env.BRANCH_NAME }}"
                
                # Now push. If the rebase has no conflicts, it will succeed.
                git push origin HEAD:${{ env.BRANCH_NAME }}
            else
                echo "No formatting changes to commit."
            fi
